// Jigsaw-assembly ("ประกอบรูปภาพ") spatial-reasoning test.
//
// Each question is built from one shape family (cross, triangle, circle,
// star, hexagon, rect). The 5 choices for that family are generated by
// stratified-sampling the family's "dominant" size/shape parameter into 5
// non-overlapping bands with a margin between them — this *guarantees* every
// pair of the 5 choices is visually distinguishable, unlike plain rejection
// sampling (which can rarely exhaust its retry budget and fall back to two
// near-identical choices when the parameter range is tight — verified via a
// 2000-iteration simulation during development that caught exactly this).
//
// One of the 5 instances is picked as the "target" and cut into exactly 2
// pieces via a pre-validated diagonal (see polygon.ts) — correct by
// construction, no float-precision line-clipping that could leave a gap.
// Two interaction modes share this generation:
//   - "fragments-to-whole": show the target's 2 cut pieces, pick which of
//     the 5 whole shapes they assemble into.
//   - "whole-to-fragments": show the target's whole shape, pick which of 5
//     piece-pairs (one cut per instance, including the target) assembles
//     into it.

import { Point, Polygon, centroid, rotate, splitAtVertices, splitTriangle } from "@/lib/polygon";

export type ShapeFamily = "cross" | "triangle" | "circle" | "star" | "hexagon" | "rect";
export type Mode = "fragments-to-whole" | "whole-to-fragments";

export const TOTAL_QUESTIONS = 20;
export const TOTAL_TIME = 600; // seconds (10 minutes)
export const CHOICE_COUNT = 5;

function rand(min: number, max: number): number {
  return min + Math.random() * (max - min);
}

function choice<T>(arr: T[]): T {
  return arr[Math.floor(Math.random() * arr.length)];
}

// Splits [min, max] into `count` equal bands, shuffles which band maps to
// which output slot, and samples each value from the inner 30% of its band —
// so any two sampled values are guaranteed at least 0.35*bandWidth*2 apart,
// keeping even the worst-case (two choices landing in adjacent bands) large
// enough to read as visually distinct once rendered.
function stratifiedSample(min: number, max: number, count: number): number[] {
  const bandWidth = (max - min) / count;
  const order = Array.from({ length: count }, (_, i) => i);
  for (let i = order.length - 1; i > 0; i--) {
    const j = Math.floor(Math.random() * (i + 1));
    [order[i], order[j]] = [order[j], order[i]];
  }
  return order.map((band) => {
    const bandStart = min + band * bandWidth;
    return bandStart + bandWidth * 0.35 + Math.random() * bandWidth * 0.3;
  });
}

// ---- shape family generators (all normalized to roughly fit a -50..50 box) ----

function crossPoly(armWidth: number): Polygon {
  const s = 45;
  const w = armWidth;
  return [
    [-w, -s], [w, -s], [w, -w], [s, -w], [s, w], [w, w],
    [w, s], [-w, s], [-w, w], [-s, w], [-s, -w], [-w, -w],
  ];
}
function trianglePoly(apexDx: number): Polygon {
  return [[apexDx, -50], [45, 35], [-45, 35]];
}
function circlePoly(r: number, n = 16): Polygon {
  return Array.from({ length: n }, (_, i) => {
    const a = (i / n) * 2 * Math.PI - Math.PI / 2;
    return [r * Math.cos(a), r * Math.sin(a)] as Point;
  });
}
function starPoly(outerR: number, innerR: number): Polygon {
  const pts: Polygon = [];
  for (let i = 0; i < 10; i++) {
    const r = i % 2 === 0 ? outerR : innerR;
    const a = (i / 10) * 2 * Math.PI - Math.PI / 2;
    pts.push([r * Math.cos(a), r * Math.sin(a)]);
  }
  return pts;
}
function hexagonPoly(r: number): Polygon {
  return Array.from({ length: 6 }, (_, i) => {
    const a = (i / 6) * 2 * Math.PI - Math.PI / 2;
    return [r * Math.cos(a), r * Math.sin(a)] as Point;
  });
}
function rectPoly(w: number, h: number, skew: number): Polygon {
  return [
    [-w / 2 + skew, -h / 2], [w / 2 + skew, -h / 2],
    [w / 2 - skew, h / 2], [-w / 2 - skew, h / 2],
  ];
}

interface ShapeInstance {
  family: ShapeFamily;
  poly: Polygon;
}

const FAMILIES: ShapeFamily[] = ["cross", "triangle", "circle", "star", "hexagon", "rect"];

// Each family's dominant parameter range (stratified across the 5 choices)
// plus how to build a polygon from that dominant value (secondary
// parameters, if any, are randomized independently per instance).
const FAMILY_SPECS: Record<ShapeFamily, { range: [number, number]; build: (dominant: number) => Polygon }> = {
  cross: { range: [10, 22], build: (w) => crossPoly(w) },
  triangle: { range: [-22, 22], build: (dx) => trianglePoly(dx) },
  circle: { range: [30, 50], build: (r) => circlePoly(r) },
  star: { range: [38, 52], build: (outerR) => starPoly(outerR, rand(12, 26)) },
  hexagon: { range: [30, 50], build: (r) => hexagonPoly(r) },
  rect: { range: [-20, 20], build: (skew) => rectPoly(rand(70, 95), rand(45, 68), skew) },
};

function buildFamilyInstances(family: ShapeFamily): ShapeInstance[] {
  const spec = FAMILY_SPECS[family];
  const dominants = stratifiedSample(spec.range[0], spec.range[1], CHOICE_COUNT);
  return dominants.map((d) => ({ family, poly: spec.build(d) }));
}

// Vertex-index pairs verified (see scratchpad validation) to be interior
// diagonals with a reasonably balanced area split (>=15% each side) across
// the full parameter range of each family.
const VERTEX_CUTS: Record<Exclude<ShapeFamily, "triangle">, [number, number][]> = {
  cross: [[0, 6], [2, 8], [0, 5], [1, 8], [3, 9], [4, 10]],
  circle: [[0, 8], [0, 6], [0, 10], [2, 10], [4, 12]],
  star: [[0, 5], [1, 6], [2, 7], [3, 8], [4, 9]],
  hexagon: [[0, 3], [1, 4], [2, 5]],
  rect: [[0, 2], [1, 3]],
};

function cutInstance(instance: ShapeInstance): [Polygon, Polygon] {
  if (instance.family === "triangle") {
    const vertexIndex = Math.floor(Math.random() * 3);
    const t = rand(0.35, 0.65);
    return splitTriangle(instance.poly, vertexIndex, t);
  }
  const [i, j] = choice(VERTEX_CUTS[instance.family]);
  return splitAtVertices(instance.poly, i, j);
}

// Rotates a piece randomly around its own centroid, purely for display —
// scattered/rotated fragments, matching the reference material's look, and
// forcing the test taker to mentally rotate pieces back into place.
function scatterPiece(piece: Polygon): Polygon {
  return rotate(piece, rand(0, 360), centroid(piece));
}

export interface JigsawChoice {
  whole?: Polygon;
  pieces?: [Polygon, Polygon];
}

export interface JigsawQuestion {
  mode: Mode;
  promptPieces?: [Polygon, Polygon];
  promptWhole?: Polygon;
  choices: JigsawChoice[];
  correctIndex: number;
}

function generateQuestion(mode: Mode): JigsawQuestion {
  const family = choice(FAMILIES);
  const instances = buildFamilyInstances(family);
  const correctIndex = Math.floor(Math.random() * CHOICE_COUNT);
  const target = instances[correctIndex];

  if (mode === "fragments-to-whole") {
    const [a, b] = cutInstance(target);
    return {
      mode,
      promptPieces: [scatterPiece(a), scatterPiece(b)],
      choices: instances.map((inst) => ({ whole: inst.poly })),
      correctIndex,
    };
  }

  return {
    mode,
    promptWhole: target.poly,
    choices: instances.map((inst) => {
      const [a, b] = cutInstance(inst);
      return { pieces: [scatterPiece(a), scatterPiece(b)] as [Polygon, Polygon] };
    }),
    correctIndex,
  };
}

export function generateSet(mode: Mode): JigsawQuestion[] {
  return Array.from({ length: TOTAL_QUESTIONS }, () => generateQuestion(mode));
}
